export const Images = {
	powdersprings: require("./powdersprings.jpg"),
	marietta: require("./marietta.jpg"),
	tennis: require("./tennis.jpg"),
	alm: require("./alm.jpg"),
	basket: require("./basket.jpg"),
	racquet: require("./racquet.jpg"),
	football: require("./football.jpg"),
	baseball: require("./baseball.jpg"),
	soccer: require("./soccer.jpg"),
	pingball: require("./pingball.jpg"),
	icehockey: require("./icehockey.jpg"),
	swimming: require("./swimming.jpg"),
	yoga: require("./yoga.jpg"),
	pilets: require("./pilets.jpg"),
	horseride: require("./horseride.jpg"),
	iconCircled: require("./icon-circled.png"),
	pluesIcon: require("./addimage.svg"),
	dropdate: require("./datedropdown.svg"),
	lesson: require("./lesson.png"),
	lessonRed: require("./lesson-red.png"),
	homebanner:require("./homebanner.jpg"),
	baseballHomebanner :require("./baseball-homebanner.jpg"),
	pickleballHomebanner :require("./pickleballhomebanner.jpg")
};
