export const Constants = {
    FETCH_LOGIN: "FETCH_LOGIN",
    FETCH_PARTNER : "FETCH_PARTNER",
    FETCH_CENTER : "FETCH_CENTER",
    FETCH_ACCOUNT : "FETCH_ACCOUNT",
    FETCH_TIMEZONE : "FETCH_TIMEZONE",
    FETCH_CENTERSLIST : "FETCH_CENTERSLIST"
  };